version: '3.8'

services: 
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: db
      DB_PORT: 3306
      DB_NAME: student
      DB_USERNAME: root
      DB_PASSWORD: admin

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_DATABASE: student
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
 mysql_data: